[master]
  version = 1
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20171113234252-7750b12/master-haskell-20171113234252-7750b12"
  sha1 = "1dd2df33e187920050114f62aa8de3cdd04fe595"

[global]
  CACHE = "true"
  WARNINGS = "false"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
